
interface IHTMLElementProps {
    style?:string;
    id?:string|number;
    onClick?:(e:Event)=>void;
    className?: string;
    htmlFor?: string;
}

interface IIFrameProps extends IHTMLElementProps{
    frameBorder?:number|string;
    src?:string;
    onLoad?:(e:Event)=>void;
    onError?:(e:Event)=>void;
}

interface ILInkProps extends IHTMLElementProps{
    href?:string;
    target?:string;
}

declare namespace JSX {
    // tslint:disable-next-line:interface-name
    export interface IntrinsicElements {
        a:ILInkProps;
        abbr:IHTMLElementProps;
        acronym:IHTMLElementProps;
        address:IHTMLElementProps;
        applet:IHTMLElementProps;
        area:IHTMLElementProps;
        article:IHTMLElementProps;
        aside:IHTMLElementProps;
        audio:IHTMLElementProps;
        b:IHTMLElementProps;
        base:IHTMLElementProps;
        basefont:IHTMLElementProps;
        bb:IHTMLElementProps;
        bdo:IHTMLElementProps;
        big:IHTMLElementProps;
        blockquote:IHTMLElementProps;
        body:IHTMLElementProps;
        br:IHTMLElementProps;
        button:IHTMLElementProps;
        canvas:IHTMLElementProps;
        caption:IHTMLElementProps;
        center:IHTMLElementProps;
        cite:IHTMLElementProps;
        code:IHTMLElementProps;
        col:IHTMLElementProps;
        colgroup:IHTMLElementProps;
        command:IHTMLElementProps;
        datagrid:IHTMLElementProps;
        datalist:IHTMLElementProps;
        dd:IHTMLElementProps;
        del:IHTMLElementProps;
        details:IHTMLElementProps;
        dfn:IHTMLElementProps;
        dialog:IHTMLElementProps;
        dir:IHTMLElementProps;
        div:IHTMLElementProps;
        dl:IHTMLElementProps;
        dt:IHTMLElementProps;
        em:IHTMLElementProps;
        embed:IHTMLElementProps;
        eventsource:IHTMLElementProps;
        fieldset:IHTMLElementProps;
        figcaption:IHTMLElementProps;
        figure:IHTMLElementProps;
        font:IHTMLElementProps;
        footer:IHTMLElementProps;
        form:IHTMLElementProps;
        frame:IHTMLElementProps;
        frameset:IHTMLElementProps;
        h1:IHTMLElementProps;
        h2:IHTMLElementProps;
        h3:IHTMLElementProps;
        h4:IHTMLElementProps;
        h5:IHTMLElementProps;
        h6:IHTMLElementProps;
        head:IHTMLElementProps;
        header:IHTMLElementProps;
        hgroup:IHTMLElementProps;
        hr:IHTMLElementProps;
        html:IHTMLElementProps;
        i:IHTMLElementProps;
        iframe:IIFrameProps;
        img:IHTMLElementProps;
        input:IHTMLElementProps;
        ins:IHTMLElementProps;
        isindex:IHTMLElementProps;
        kbd:IHTMLElementProps;
        keygen:IHTMLElementProps;
        label:IHTMLElementProps;
        legend:IHTMLElementProps;
        li:IHTMLElementProps;
        link:IHTMLElementProps;
        map:IHTMLElementProps;
        mark:IHTMLElementProps;
        menu:IHTMLElementProps;
        meta:IHTMLElementProps;
        meter:IHTMLElementProps;
        nav:IHTMLElementProps;
        noframes:IHTMLElementProps;
        noscript:IHTMLElementProps;
        object:IHTMLElementProps;
        ol:IHTMLElementProps;
        optgroup:IHTMLElementProps;
        option:IHTMLElementProps;
        output:IHTMLElementProps;
        p:IHTMLElementProps;
        param:IHTMLElementProps;
        pre:IHTMLElementProps;
        progress:IHTMLElementProps;
        q:IHTMLElementProps;
        rp:IHTMLElementProps;
        rt:IHTMLElementProps;
        ruby:IHTMLElementProps;
        s:IHTMLElementProps;
        samp:IHTMLElementProps;
        script:IHTMLElementProps;
        section:IHTMLElementProps;
        select:IHTMLElementProps;
        small:IHTMLElementProps;
        source:IHTMLElementProps;
        span:IHTMLElementProps;
        strike:IHTMLElementProps;
        strong:IHTMLElementProps;
        style:IHTMLElementProps;
        sub:IHTMLElementProps;
        sup:IHTMLElementProps;
        table:IHTMLElementProps;
        tbody:IHTMLElementProps;
        td:IHTMLElementProps;
        textarea:IHTMLElementProps;
        tfoot:IHTMLElementProps;
        th:IHTMLElementProps;
        thead:IHTMLElementProps;
        time:IHTMLElementProps;
        title:IHTMLElementProps;
        tr:IHTMLElementProps;
        track:IHTMLElementProps;
        tt:IHTMLElementProps;
        u:IHTMLElementProps;
        ul:IHTMLElementProps;
        var:IHTMLElementProps;
        video:IHTMLElementProps;
        wbr:IHTMLElementProps;
    }
}
