import {Game} from "@engine/core/game";
import {KeyboardControl} from "@engine/control/keyboard/keyboardControl";
import {GamePadControl} from "@engine/control/gamepad/gamePadControl";
import {MouseControl} from "@engine/control/mouse/mouseControl";
import {CanvasRenderer} from "@engine/renderer/canvas/canvasRenderer";
import {IntroScene} from "./scenes/introScene";
import {ResourceLoader} from "@engine/resources/resourceLoader";
import {AbstractCanvasRenderer} from "@engine/renderer/abstract/abstractCanvasRenderer";
import {DI} from "@engine/core/ioc";
import {WebGlRenderer} from "@engine/renderer/webGl/renderer/webGlRenderer";

ResourceLoader.BASE_URL = './x0_5/assets';
const game = new Game({width:240,height:320});
DI.registerInstance(game);
game.setRenderer(CanvasRenderer);
(game.getRenderer() as AbstractCanvasRenderer).setPixelPerfect(true);
game.addControl(KeyboardControl);
game.addControl(GamePadControl);
game.addControl(MouseControl);
const scene = new IntroScene(game);
game.runScene(scene);
